-- واصل بيتك / بوابة الكرك
-- شغّل هذا الملف مرة واحدة داخل Supabase SQL Editor

create table if not exists merchants (
    id bigint generated by default as identity primary key,
    name text not null,
    category text,
    phone text,
    location text,
    status text default 'قيد المراجعة',
    image_data text default ''
);

create table if not exists products (
    id bigint generated by default as identity primary key,
    merchant_name text not null,
    item_name text not null,
    price numeric default 0,
    quantity text default '1',
    unit text default 'وجبة',
    image_path text default ''
);

create table if not exists customers (
    id bigint generated by default as identity primary key,
    name text,
    phone text unique,
    address text
);

create table if not exists orders (
    id bigint generated by default as identity primary key,
    customer_name text,
    customer_phone text,
    customer_address text,
    order_details text,
    total_amount numeric default 0,
    payment_method text,
    order_status text default 'قيد التجهيز',
    driver_name text default '',
    lat numeric default 31.1854,
    lng numeric default 35.7048,
    created_at text
);

create table if not exists drivers (
    id bigint generated by default as identity primary key,
    name text,
    phone text,
    vehicle_type text,
    status text
);

create table if not exists offers (
    id bigint generated by default as identity primary key,
    title text,
    discount_details text,
    valid_until text
);

alter table merchants enable row level security;
alter table products enable row level security;
alter table offers enable row level security;
alter table customers enable row level security;
alter table orders enable row level security;

drop policy if exists "public read merchants" on merchants;
create policy "public read merchants" on merchants for select using (true);

drop policy if exists "public read products" on products;
create policy "public read products" on products for select using (true);

drop policy if exists "public read offers" on offers;
create policy "public read offers" on offers for select using (true);

drop policy if exists "public insert customers" on customers;
create policy "public insert customers" on customers for insert with check (true);

drop policy if exists "public update customers" on customers;
create policy "public update customers" on customers for update using (true) with check (true);

drop policy if exists "public insert orders" on orders;
create policy "public insert orders" on orders for insert with check (true);

drop policy if exists "public read orders" on orders;
create policy "public read orders" on orders for select using (true);

-- الإدارة تستخدم SUPABASE_SERVICE_KEY ولا نفتح كتابة المتاجر والأصناف للزبون.
